-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 00:27:09 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LogAnalyDB
-- -----------------------------------------------------
-- 日志分析库

-- -----------------------------------------------------
-- Schema LogAnalyDB
--
-- 日志分析库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LogAnalyDB` DEFAULT CHARACTER SET utf8 ;
USE `LogAnalyDB` ;

-- -----------------------------------------------------
-- Table `LogAnalyDB`.`LogFlowTZT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LogAnalyDB`.`LogFlowTZT` (
  `Pack_ID` VARCHAR(256) NOT NULL COMMENT '包ID，数据包的唯一标识',
  `TimeStamp` VARCHAR(24) NOT NULL COMMENT '记录包的处理时间',
  `Action` VARCHAR(45) NULL COMMENT '包的功能号，具体参见投资堂（中焯）的说明文档',
  `Status` VARCHAR(3) NULL COMMENT '包的状态，成功还是失败：\n“ok” 正常\n\"err\" 失败',
  `ServerIP` VARCHAR(15) NULL COMMENT '日志所在服务器的IP',
  `LogContent` JSON NULL COMMENT '日志的具体内容，为json格式',
  PRIMARY KEY (`Pack_ID`, `TimeStamp`),
  INDEX `Action` (`Action` ASC),
  INDEX `Status` (`Status` ASC),
  INDEX `TimeStamp` (`TimeStamp` ASC))
ENGINE = InnoDB
COMMENT = '投资堂（中焯）日志流水表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
